### ISSUE TITLE
slightly modified

### ISSUE THREAD

**Issue by gamegam** [ethaniccc/Mockingbird#127]
Now you fix it.

Currently Found: Tingling on Touch

https://github.com/gamegam/MockingbirdAntiHacker

**Comment by ethaniccc** [comment]
All you did was change the `mcpe-protocol` in `plugin.yml`....

I'm not obligated to do anything, especially update this project I no longer have interest in updating.
If someone wants to make a fix they can feel free to make a pull request or maintain their own fork, but otherwise - this project will remain stale.

**Comment by Cqdet** [comment]
shut up
