### ISSUE TITLE
Improving MockingBird

### ISSUE THREAD

**Issue by LichareKEK** [ethaniccc/Mockingbird#62]
Hello. This issue will be on my thoughts on how to improve Mockingbird's current state.
As of now, you can't really use it on public servers with circa 20/25+ players. The anticheat is just too unstable.

What I would like to see from the devs of this amazing project is a reorganization (even a rewrite if you want...) of the plugin. Create more stable checks. Even if it doesn't detect less blatant cheats, it won't falsely punish random players. We don't really care about 80+% Velocity, AimAssist, 3.05 Reach, 1.01 Timer etc. Focus on the most used cheats, as Speed, Fly.... and make them stable

I really believe in this project, also because it's the only active anticheat at the moment.

**Comment by ethaniccc** [comment]
Most of the movement checks should be stable, like Fly, Speed, etc. As for the stability of the combat checks, well, they're not stable. 

As for the rewrite, I don't plan on doing a full rewrite (yet?), but I am planning on changing the way modules are done, making them more customizable, so that users can change the sensitivity of modules and messages without needing to edit the source code of the plugin.

I know that Mockingbird may be unstable (maybe even very unstable, as you have mentioned), which is why I decided to add the "reset violations" feature.

If there's anything else you want to suggest to improve Mockingbird, feel free to say so :D

**Comment by ethaniccc** [comment]
Having the ability to change check sensitivity has been done, any other suggestions :D ?

**Comment by ethaniccc** [comment]
A rewrite has been done with v2, if you have any more suggestions feel free to reach out and I will re-open this issue
