### ISSUE TITLE
When you fly with an Elytra you get kicked

### ISSUE THREAD

**Issue by ghost** [ethaniccc/Mockingbird#92]
Fix it please 🤧

**Comment by ghost** [comment]
Fix it like RN! The Owner said she burns every Elytra bc of this so please fix this 🤧 It took to long for me to get this!

**Comment by john-bv** [comment]
What server

**Comment by ghost** [comment]
An Minecraft Server 👁👄👁

**Comment by ghost** [comment]
> What server

I dont say it bc of Hate& Co

**Comment by ethaniccc** [comment]
What version of Mockingbird are you using (don't say latest)

**Comment by ghost** [comment]
The newest / latest ._.

**Comment by ethaniccc** [comment]
> **(don't say latest)**

I don't know what's "newest/latest" for you, as you might not have seen new updates in the anti-cheat. Maybe you haven't seen the actual latest release (v2.4) and are still using v2.3 thinking that's the latest.

**Comment by ghost** [comment]
> > **(don't say latest)**
> 
> I don't know what's "newest/latest" for you, as you might not have seen new updates in the anti-cheat. Maybe you haven't seen the actual latest release (v2.4) and are still using v2.3 thinking that's the latest.

She uses v2.4 (I've asked her)

**Comment by ethaniccc** [comment]
Hmm... I thought I fixed this issue in v2.4 - looks like I'll have to do more testing (darn it), thanks for reporting!

**Comment by ghost** [comment]
No Problem! But please fix it ASAP! I dont want my Elytra to get burned 🤧

**Comment by ghost** [comment]
@ethaniccc Thanks for fixing it! Heres a Diamond 💎

**Comment by ethaniccc** [comment]
> @ethaniccc Thanks for fixing it! Heres a Diamond 💎

Unfortunatley I didn't fix it in the latest commit (that commit only has threaded reach checks and a threaded hitbox check)

When I fix this, the issue will be tagged in the commit description

**Comment by UnEnanoMas** [comment]
@tim51159 


# Speed
SpeedA:
  enabled: true
  punish: true
  punishment_type: kick
  suppression: false
  max_violations: 25
  # check sensitivity settings
  max_breach: 0.30000
SpeedB:
  enabled: true
  punish: true
  punishment_type: kick
  suppression: false
  max_violations: 25
  # check sensitivity settings
  max_speed_on_ground: 0.30
  max_speed_off_ground: 3.00

This is what I use so that the game does not expel players with elytras, I have been testing it until I have verified that it works correctly. The only bad thing is that it will not detect the speed hack so fast xd

**Comment by ethaniccc** [comment]
Fixed in 97c53c8
