### ISSUE TITLE
Detected fly when on certain blocks

### ISSUE THREAD

**Issue by callumrawlinson** [ethaniccc/Mockingbird#95]
Hello Ethan,
Mockingbird sometimes detects that people are flying when jumping or walking on half slabs or stairs

**Comment by ethaniccc** [comment]
Please include the following:
- Check variant (there are currently four fly checks)
- Cheat probability and amount of falses (if the probability is higher than low and the violations go above 2 then I'll consider fixing it)
- Version (include dev build number if you are using a dev-build)
- Visual proof, such as a video

**Comment by callumrawlinson** [comment]
Ethan, hi its me again, from versai,
i am using the latest version from github.
the probability was over 70% and there was maybe 10-11 violations
also ethan do you know what diverses github is?
known as brady?

**Comment by ethaniccc** [comment]
give a specific dev build version please
the reason I say this is because there are multiple branches on GitHub, and I don't know if you are using the one on the stable branch or the v2 branch
on top of that include a video of the falses if possible :p
(also please try to do off-topic inquiries on Discord please)

**Comment by callumrawlinson** [comment]
my version is v2 and i will send you a video when im home after

**Comment by ethaniccc** [comment]
Yes there is a test server, read https://github.com/ethaniccc/Mockingbird#witherhosting
Also are you using the `stable` branch or the `v2` branch?

**Comment by callumrawlinson** [comment]
the v2 branch
